debug: false
data.backup.frequency.sec: -1
locale: en

yearmarked-worlds: 
  - world


#MONSOONDAY
yearmarked-monsoonday: Monsoonday
yearmarked-monsoonday-rain: true
yearmarked-monsoonday-allow-rain-toggle-with-thordfish: true
yearmarked-monsoonday-rain-toggle-on-with-thordfish-cost: 0
yearmarked-monsoonday-rain-toggle-off-with-thordfish-cost: 0


#EARTHDAY
yearmarked-earthday: Earthday
yearmarked-earthday-bonus-crops: true
yearmarked-earthday-bonus-crops-range-high: 3
yearmarked-earthday-bonus-crops-range-low: 1

#WORTTAG
yearmarked-wortag: Wortag
yearmarked-wortag-bonus-crops: true
yearmarked-wortag-bonus-crops-range-high: 3
yearmarked-wortag-bonus-crops-range-low: 1


#DONNERSTAG
yearmarked-donnerstag: Donnerstag
yearmarked-donnerstag-lightning: true
yearmarked-donnerstag-allow-lightning-toggle-with-thordfish: true
yearmarked-donnerstag-lightning-toggle-on-with-thordfish-cost: 0
yearmarked-donnerstag-lightning-toggle-off-with-thordfish-cost: 1
yearmarked-donnerstag-allow-super-creeper-spawn-with-fish-sword: true
yearmarked-donnerstag-super-creeper-spawn-with-fish-sword-percent-chance: 100
yearmarked-donnerstag-super-creeper-drops-diamond-percent-chance: 5
yearmarked-donnerstag-super-creeper-drops-emerald-percent-chance: 10
yearmarked-donnerstag-super-creeper-drops-thordfish-percent-chance: 15


#FISHFRYTAG
yearmarked-fishfryday-donnerstag-super-creeper-op-luck: true
yearmarked-fishfryday: Fishfryday
yearmarked-fishfryday-bonus-xp-multiplier: 2
yearmarked-fishfryday-percent-chance-diamond: 1
yearmarked-fishfryday-percent-chance-emerald: 10
yearmarked-fishfryday-percent-chance-grass: 15
yearmarked-fishfryday-percent-chance-thordfish: 10
yearmarked-fishfryday-op-luck: true


#DIAMONDAY
yearmarked-diamonday: Diamonday
yearmarked-diamonday-bonus-diamonds: true
yearmarked-diamonday-bonus-diamonds-range-high: 3
yearmarked-diamonday-bonus-diamonds-range-low: 1

#FEATHERSDAY
yearmarked-feathersday: Feathersday
yearmarked-feathersday-prevent-fall-damage: true
yearmarked-feathersday-bounce: true
yearmarked-feathersday-bounce-xz-multiplier: 2.5





recipes-worlds: 
  - world

recipes: 
  - thord-fish
  - diamond-day-sword
  - fish-sword
  - fish-arrow
  
recipe.thord-fish.name: Thordfish

recipe.thord-fish.rows: 
  - FAF
  - AAA
  - FAF
  
recipe.thord-fish.mats: 
  - F=RAW_FISH
  - A=AIR
  
recipe.thord-fish.output: RAW_FISH

recipe.thord-fish.op.only: false


#FISH NEEDLE
recipe.fish-sword.name: Needle

recipe.fish-sword.rows: 
  - AFA
  - AFA
  - ASA
  
recipe.fish-sword.mats: 
  - F=RAW_FISH
  - A=AIR
  - S=STICK
  
recipe.fish-sword.output: STONE_SWORD

recipe.fish-sword.item.starts.with:
  - 4=Thordfish


#DIAMOND NEEDLE
recipe.diamond-day-sword.name: Needle

recipe.diamond-day-sword.rows: 
  - ADA
  - ADA
  - ANA
  
recipe.diamond-day-sword.mats: 
  - D=DIAMOND
  - N=STONE_SWORD
  - A=AIR
  
recipe.diamond-day-sword.output: DIAMOND_SWORD

recipe.diamond-day-sword.item.starts.with:
  - 1=Diamonday DIAMOND
  - 4=Diamonday DIAMOND
  - 7=Needle
  
#FISH ARROW
recipe.fish-arrow.name: Fishbone Arrow

recipe.fish-arrow.rows: 
  - AAA
  - AFA
  - ASA
  
recipe.fish-arrow.mats: 
  - F=RAW_FISH
  - A=AIR
  - S=STICK
recipe.fish-arrow.output: ARROW
recipe.fish-arrow.amount: 16
recipe.fish-arrow.item.starts.with: 
  - 4=Thordfish
  