name: Yearmarked
version: 1.0.3
main:  com.blocktyper.yearmarked.YearmarkedPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Keeps track of days/months/years and triggers special events in game

commands:
  change-time:
    description: changes time forward or backward by the amount provided by the foirst argument
  chtm: 
    description: changes time forward or backward by the amount provided by the foirst argument